# █▄█ █▄█ █▀█ █▀█ █░ ▄▀█ █▄░█ █▀▄  ▄▀█ █░█ ▀█▀ █▀█ █▀ ▀█▀ ▄▀█ █▀█ ▀█▀  █▀ █▀█ █▄░█ █▀ █ █▀▀
# █░█ ░█░ █▀▀ █▀▄ █▄ █▀█ █░▀█ █▄▀  █▀█ █▄█ ░█░ █▄█ ▄█ ░█░ █▀█ █▀▄ ░█░  █▄ █▄█ █░▀█ █▀ █ █▄█

# █▀ █▀█ █▀█ █▀▀  █▀ █▄█ █▀ ▀█▀ █▀▀ █▀▄▀█  █▀ █▀▀ █▀█ █░█ █ █▀ █▀▀ █▀
# █▄ █▄█ █▀▄ ██▄  ▄█ ░█░ ▄█ ░█░ ██▄ █░▀░█  ▄█ ██▄ █▀▄ ▀▄▀ █ █▄ ██▄ ▄█
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP GBM_BACKEND __GLX_VENDOR_LIBRARY_NAME LIBVA_DRIVER_NAME WLR_DRM_DEVICES WLR_RENDER_DRM_DEVICE WLR_NO_HARDWARE_CURSORS
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP GBM_BACKEND __GLX_VENDOR_LIBRARY_NAME LIBVA_DRIVER_NAME WLR_DRM_DEVICES WLR_RENDER_DRM_DEVICE WLR_NO_HARDWARE_CURSORS
exec-once = sleep 1 && systemctl --user restart xdg-desktop-portal-hyprland.service xdg-desktop-portal.service

# Authentication agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Hyprland plugins
exec-once = hyprpm reload -n

# GNOME settings
exec-once = gsettings set org.gnome.desktop.wm.preferences button-layout appmenu

# Default browser
exec-once = xdg-settings set default-web-browser firefox.desktop

# █░█ █▀ █▀▀ █▀█  █▀ █▀▀ █▀█ █░█ █ █▀ █▀▀ █▀  ( █░█ █ ▄▀█  █▀ █▄█ █▀ ▀█▀ █▀▀ █▀▄▀█ █▀▄ )
# █▄█ ▄█ ██▄ █▀▄  ▄█ ██▄ █▀▄ ▀▄▀ █ █▄ ██▄ ▄█  ( ▀▄▀ █ █▀█  ▄█ ░█░ ▄█ ░█░ ██▄ █░▀░█ █▄▀ )
exec-once = systemctl --user start ags.service
exec-once = systemctl --user start walker.service
exec-once = systemctl --user start elephant.service
exec-once = systemctl --user start mako.service
exec-once = systemctl --user start awww-daemon.service
exec-once = systemctl --user start hypridle.service
exec-once = systemctl --user start bluetooth-reconnect.service

# █▀█ █▄░█ █▀▀ ─ █▀ █▄█ █▀█ ▀█▀  █░█ ▀█▀ █ █░ █ ▀█▀ █ █▀▀ █▀
# █▄█ █░▀█ ██▄ ─ ▄█ █░█ █▄█ ░█░  █▄█ ░█░ █ █▄ █ ░█░ █ ██▄ ▄█
exec-once = system-pick-wallpaper

# Clipboard managers (need to stay as exec-once)
exec-once = wl-paste -p --watch wl-copy -pc
exec-once = clipse -listen

# ▄▀█ █▀█ █▀█ █░ █ █▀ ▄▀█ ▀█▀ █ █▀█ █▄░█  █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀
# █▀█ █▀▀ █▀▀ █▄ █ █▄ █▀█ ░█░ █ █▄█ █░▀█  █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█
# Application-level shortcuts (Alt+C/V for copy/paste) are handled by keyd
# Configured via system/keyd/default.conf

exec-once = hyprsession
