source = ./gpu.conf
source = ./monitors.conf
source = ./env.conf
source = ./input.conf
source = ./misc.conf
source = ./plugins.conf
source = ./animations.conf
source = ./keybindings.conf
source = ./windowrules.conf
source = ./themes/common.conf
source = ./themes/theme.conf
source = ./themes/colors.conf
source = ./autostart.conf
source = ./userprefs.conf

# Permissions (kept in main file)
permission = /usr/bin/grim, screencopy, allow
permission = /usr/local/bin/grim, screencopy, allow
permission = /usr/lib/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/libexec/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/lib64/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/bin/hyprpm, plugin, allow
permission = /usr/local/bin/hyprpm, plugin, allow
