general {
    lock_cmd = pgrep -x hyprlock > /dev/null || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = pkill -x hyprlock 2>/dev/null; sleep 3; hyprlock & sleep 1; swww query 2>/dev/null || swww-daemon; sleep 0.2; swww img ~/.config/hypr/wallpapers/current/current_wallpaper.jpg --transition-type grow --transition-pos 0.2,0.2 --transition-step 90 2>/dev/null || true; systemctl --user restart ags.service; system-bluetooth-reconnect
    inhibit_sleep = 3
}

listener {
    timeout = 120 # 2min - dim before lock
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

listener {
    timeout = 300 # 5min - lock
    on-timeout = loginctl lock-session
}

listener {
    timeout = 7200  # 2h - screen off
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 9000  # 2h30 - suspend
    on-timeout = systemctl suspend || loginctl suspend
}
