pragma Singleton

// Theme variables (Generated by matugen — do not edit)
// Material You palette mapped onto base16 slots, mirroring the AGS theme
// so both shells stay visually identical.

import Quickshell
import QtQuick

Singleton {
    // Background / surface ramp (darkest -> lightest)
    readonly property color base00: "#121318" // Background
    readonly property color base01: "#121318" // Surface
    readonly property color base02: "#292a2f" // Selection
    readonly property color base03: "#34343a" // Lines / comments
    readonly property color base04: "#c6c5d0" // Muted text
    readonly property color base05: "#e3e1e9" // Text
    readonly property color base06: "#e3e1e9" // Light text
    readonly property color base07: "#e3e1e9" // Primary text

    // Accent colors (Material You roles mapped to base16 hue slots)
    readonly property color base08: "#ffb4ab" // Red    -> error
    readonly property color base09: "#c2c5dd" // Orange -> secondary
    readonly property color base0A: "#e4bad9" // Yellow -> tertiary
    readonly property color base0B: "#b7c4ff" // Green  -> primary
    readonly property color base0C: "#5c3d56" // Cyan   -> tertiary container
    readonly property color base0D: "#b7c4ff" // Blue   -> primary
    readonly property color base0E: "#424659" // Purple -> secondary container
    readonly property color base0F: "#e4bad9" // Mauve  -> tertiary
}
