// Colors.qml is generated by matugen and lives at ~/.config/quickshell/Colors.qml.
// Template: ~/.config/matugen/templates/quickshell-colors.qml
// Run `matugen image <wallpaper>` to regenerate it. Quickshell hot-reloads on change.
import Quickshell
import qs.bar

ShellRoot {
    Variants {
        model: Quickshell.screens

        Bar {
            required property var modelData
            screen: modelData
        }
    }
}
