# █▀▀ █░█ █▀▀ █▀▀ █▄░█ █▀ █▀▀  █▀ █▀█ █▄░█ █▀ █ █▀▀
# █▄█ █▄█ ██▄ ██▄ █░▀█ ▄█ ██▄  █▄ █▄█ █░▀█ █▀ █ █▄█
# Border colors — static fallback until Hyprland matugen output is enabled

general {
    col.active_border = rgba(113,113,113,0.05)
    col.inactive_border = rgba(185,185,185,0.02)
}
