# Base16 Workspace - kitty color config
# Scheme by John
background #080808
foreground #e1e1e1
selection_background #4d4d4d
selection_foreground #ffffff
url_color #525252
cursor #e1e1e1
cursor_text_color #080808
active_border_color #1bfd9c
inactive_border_color #a1a1a1
bell_border_color #bababa
wayland_titlebar_color system
macos_titlebar_color system
active_tab_foreground #080808
active_tab_background #747474
inactive_tab_foreground #c0c0c0
inactive_tab_background #303030
tab_bar_background #080808

# normal
color0 #525252
color1 #7a7a7a
color2 #1bfd9c
color3 #bababa
color4 #686868
color5 #747474
color6 #868686
color7 #e1e1e1

# bright
color8 #525252
color9 #7a7a7a
color10 #1bfd9c
color11 #bababa
color12 #686868
color13 #747474
color14 #e1e1e1
color15 #ffffff

# extended base16 colors
color16 #bababa
color17 #5e5e5e
color18 #303030
color19 #4d4d4d
color20 #a1a1a1
color21 #e1e1e1