[mgr]
cwd = { fg = "#64c864" }

hovered         = { fg = "#19191c", bg = "#b4b4b4" }
preview_hovered = { fg = "#19191c", bg = "#dcdc64" }

find_keyword  = { fg = "#ffc850", italic = true }
find_position = { fg = "#ff6464", bg = "reset", italic = true }

marker_copied   = { fg = "#64c864", bg = "#64c864" }
marker_cut      = { fg = "#ff6464", bg = "#ff6464" }
marker_marked   = { fg = "#64c864", bg = "#64c864" }
marker_selected = { fg = "#b4b4b4", bg = "#b4b4b4" }

count_copied   = { fg = "#19191c", bg = "#64c864" }
count_cut      = { fg = "#19191c", bg = "#ff6464" }
count_selected = { fg = "#19191c", bg = "#b4b4b4" }

border_symbol = "│"
border_style  = { fg = "#4a4a4a" }

[tabs]
active   = { fg = "#19191c", bg = "#dcdc64", bold = true }
inactive = { fg = "#dcdc64", bg = "#262622" }

[mode]
normal_main = { fg = "#19191c", bg = "#b4b4b4", bold = true }
normal_alt  = { fg = "#b4b4b4", bg = "#262622"}

select_main = { fg = "#19191c", bg = "#64c864", bold = true }
select_alt  = { fg = "#64c864", bg = "#262622"}

unset_main  = { fg = "#19191c", bg = "#ff6464", bold = true }
unset_alt   = { fg = "#ff6464", bg = "#262622"}

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label  = { fg = "#fafafa", bold = true }
progress_normal = { fg = "#b4b4b4", bg = "#262622" }
progress_error  = { fg = "#ff6464", bg = "#262622" }

perm_type  = { fg = "#b4b4b4" }
perm_read  = { fg = "#ffc850" }
perm_write = { fg = "#ff6464" }
perm_exec  = { fg = "#64c864" }
perm_sep   = { fg = "#4a4a4a" }

[input]
border   = { fg = "#b4b4b4" }
title    = {}
value    = {}
selected = { reversed = true }

[pick]
border   = { fg = "#b4b4b4" }
active   = { fg = "#b4b4b4" }
inactive = {}

[confirm]
border     = { fg = "#b4b4b4" }
title      = { fg = "#b4b4b4" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}

[cmp]
border = { fg = "#b4b4b4" }

[tasks]
border  = { fg = "#b4b4b4" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#262622" }
cand            = { fg = "#64c864" }
rest            = { fg = "#dcdc64" }
desc            = { fg = "#b4b4b4" }
separator       = "  "
separator_style = { fg = "#4a4a4a" }

[help]
on      = { fg = "#64c864" }
run     = { fg = "#b4b4b4" }
desc    = { fg = "#dcdc64" }
hovered = { bg = "#4a4a4a", bold = true }
footer  = { fg = "#fafafa", bg = "#262622" }

[notify]
title_info  = { fg = "#64c864" }
title_warn  = { fg = "#ffc850" }
title_error = { fg = "#ff6464" }

[filetype]
rules = [
	# Media
	{ mime = "image/*", fg = "#64c864" },
	{ mime = "{audio,video}/*", fg = "#ffc850" },

	# Archives
	{ mime = "application/*zip", fg = "#b4b4b4" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#b4b4b4" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#64c864" },

	# Fallback
	{ name = "*", fg = "#fafafa" },
	{ name = "*/", fg = "#b4b4b4" }
]

[spot]
border = { fg = "#b4b4b4" }
title  = { fg = "#b4b4b4" }
tbl_cell = { fg = "#b4b4b4", reversed = true }
tbl_col = { bold = true }

[icon]
files = [
  { name = "readme", text = "󰂺", fg = "#fafafa" },
  { name = "license", text = "", fg = "#ffc850" },
  { name = "dockerfile", text = "󰡨", fg = "#b4b4b4" },
  { name = "makefile", text = "", fg = "#b4b4b4" },
  { name = "package.json", text = "", fg = "#ff6464" },
  { name = "node_modules", text = "", fg = "#ff6464" },
  { name = ".git", text = "", fg = "#ffc850" },
  { name = ".gitignore", text = "", fg = "#ffc850" },
  { name = "config", text = "", fg = "#b4b4b4" },
]
exts = [
  { name = "md", text = "", fg = "#fafafa" },
  { name = "json", text = "", fg = "#ffc850" },
  { name = "js", text = "", fg = "#ffc850" },
  { name = "ts", text = "", fg = "#b4b4b4" },
  { name = "tsx", text = "", fg = "#b4b4b4" },
  { name = "jsx", text = "", fg = "#b4b4b4" },
  { name = "py", text = "", fg = "#ffc850" },
  { name = "sh", text = "", fg = "#b4b4b4" },
  { name = "css", text = "", fg = "#b4b4b4" },
  { name = "scss", text = "", fg = "#ff6464" },
  { name = "toml", text = "", fg = "#b4b4b4" },
  { name = "yaml", text = "", fg = "#b4b4b4" },
  { name = "yml", text = "", fg = "#b4b4b4" },
  { name = "conf", text = "", fg = "#b4b4b4" },
  { name = "txt", text = "󰈙", fg = "#64c864" },
  { name = "log", text = "󰌱", fg = "#fafafa" },
  { name = "png", text = "", fg = "#b4b4b4" },
  { name = "jpg", text = "", fg = "#b4b4b4" },
  { name = "jpeg", text = "", fg = "#b4b4b4" },
  { name = "gif", text = "", fg = "#b4b4b4" },
  { name = "svg", text = "󰜡", fg = "#ffc850" },
  { name = "pdf", text = "", fg = "#b4b4b4" },
  { name = "zip", text = "", fg = "#ffc850" },
  { name = "tar", text = "", fg = "#ffc850" },
  { name = "gz", text = "", fg = "#ffc850" },
]