#!/bin/bash
# Hardware-specific package management
# Auto-generates hardware package lists based on detected hardware

# Detect CPU vendor
_detect_cpu_vendor() {
    if grep -qi "GenuineIntel" /proc/cpuinfo; then
        echo "intel"
    elif grep -qi "AuthenticAMD" /proc/cpuinfo; then
        echo "amd"
    else
        echo "unknown"
    fi
}

# Generate CPU microcode package list
_generate_cpu_packages() {
    local cpu_vendor="$1"
    
    local cpu_file="$DOTFILES_DIR/packages/hardware/cpu.package"
    
    case "$cpu_vendor" in
        intel)
            {
                echo "# Auto-generated Intel CPU packages"
                echo "# Generated: $(date '+%Y-%m-%d %H:%M:%S')"
                echo "# DO NOT EDIT - regenerated by hardware detection"
                echo ""
                echo "intel-ucode"
            } > "$cpu_file"
            log_success "Generated Intel CPU packages"
            ;;
        amd)
            {
                echo "# Auto-generated AMD CPU packages"
                echo "# Generated: $(date '+%Y-%m-%d %H:%M:%S')"
                echo "# DO NOT EDIT - regenerated by hardware detection"
                echo ""
                echo "amd-ucode"
            } > "$cpu_file"
            log_success "Generated AMD CPU packages"
            ;;
        *)
            log_warning "Unknown CPU vendor, skipping microcode"
            ;;
    esac
}

# Install CPU packages
_install_cpu_packages() {
    local cpu_vendor="$1"
    local cpu_file="$DOTFILES_DIR/packages/hardware/cpu.package"
    
    if [[ ! -f "$cpu_file" ]]; then
        log_info "No CPU packages to install"
        return
    fi
    
    local cpu_packages=()
    while IFS= read -r pkg; do
        [[ -n "$pkg" && ! "$pkg" =~ ^# ]] && cpu_packages+=("$pkg")
    done < "$cpu_file"
    
    if [[ ${#cpu_packages[@]} -gt 0 ]]; then
        log_info "Installing ${#cpu_packages[@]} CPU package(s)..."
        sudo pacman -S --needed --noconfirm "${cpu_packages[@]}"
        log_success "✓ CPU packages installed"
        echo
    fi
}

# Setup hardware packages (detect, generate lists, install, create config)
hardware_packages_setup() {
    # Setup logging if not in full install
    local standalone_mode=false
    if [[ -z "${FULL_INSTALL:-}" ]]; then
        standalone_mode=true
        init_logging "hardware"
        start_log_monitor
        trap 'stop_log_monitor; finish_logging' EXIT INT TERM
    fi

    log_section "Hardware Package Detection"

    # Detect GPU
    local has_nvidia=$(has_nvidia_gpu && echo "true" || echo "false")
    local has_amd=$(has_amd_gpu && echo "true" || echo "false")
    local has_intel=$(has_intel_gpu && echo "true" || echo "false")

    log_info "Detected GPUs:"
    [[ "$has_nvidia" == "true" ]] && log_success "  ✓ NVIDIA"
    [[ "$has_amd" == "true" ]] && log_success "  ✓ AMD"
    [[ "$has_intel" == "true" ]] && log_success "  ✓ Intel"
    echo

    # Detect CPU
    local cpu_vendor=$(_detect_cpu_vendor)
    log_info "Detected CPU: $cpu_vendor"
    echo

    # Create hardware directory if needed
    mkdir -p "$DOTFILES_DIR/packages/hardware"

    # Generate CPU microcode package list
    _generate_cpu_packages "$cpu_vendor"

    # Generate package lists for each detected GPU
    if [[ "$has_nvidia" == "true" ]]; then
        _generate_gpu_packages "nvidia"
    fi

    if [[ "$has_amd" == "true" ]]; then
        _generate_gpu_packages "amd"
    fi

    if [[ "$has_intel" == "true" ]]; then
        _generate_gpu_packages "intel"
    fi

    # Install CPU packages first
    echo
    log_section "Installing CPU Microcode"
    _install_cpu_packages "$cpu_vendor"

    # Install GPU packages
    echo
    log_section "Installing GPU Drivers"

    [[ "$has_nvidia" == "true" ]] && _install_gpu_packages "nvidia"
    [[ "$has_amd" == "true" ]] && _install_gpu_packages "amd"
    [[ "$has_intel" == "true" ]] && _install_gpu_packages "intel"

    # Post-install setup (build DKMS, load modules, etc.)
    log_section "Post-Install Setup"
    [[ "$has_nvidia" == "true" ]] && _setup_nvidia_post_install
    [[ "$has_amd" == "true" ]] && _setup_amd_post_install
    [[ "$has_intel" == "true" ]] && _setup_intel_post_install

    # Complete progress if in standalone mode
    if [[ "$standalone_mode" == "true" ]]; then
        trap - EXIT INT TERM
        stop_log_monitor
        finish_logging
        source "$DOTFILES_DIR/lib/menu.sh"
        show_completion_menu "Hardware setup complete"
    else
        log_success "✓ Hardware setup complete"
    fi
}

# Internal: Scan and generate package list for GPU type
_generate_gpu_packages() {
    local gpu_type="$1"  # nvidia, amd, or intel

    log_info "Scanning for ${gpu_type^^} packages..."

    # Define search patterns for each GPU type
    local patterns=()
    case "$gpu_type" in
        nvidia)
            patterns=("nvidia" "cuda" "optimus")
            ;;
        amd)
            patterns=("amd" "radeon" "amdvlk")
            ;;
        intel)
            patterns=("intel-media" "intel-gpu" "vulkan-intel")
            ;;
    esac

    # Get all installed packages matching patterns
    local official_packages=()
    local aur_packages=()

    for pattern in "${patterns[@]}"; do
        # Search official packages
        while IFS= read -r pkg; do
            [[ -n "$pkg" ]] && official_packages+=("$pkg")
        done < <(pacman -Qq | grep -i "$pattern" | grep -v "^lib32-")

        # Search lib32 packages separately
        while IFS= read -r pkg; do
            [[ -n "$pkg" ]] && official_packages+=("$pkg")
        done < <(pacman -Qq | grep -i "^lib32-" | grep -i "$pattern")
    done

    # Separate AUR packages
    for pkg in "${official_packages[@]}"; do
        if pacman -Qm "$pkg" &>/dev/null; then
            aur_packages+=("$pkg")
        fi
    done

    # Remove AUR packages from official list
    local official_only=()
    for pkg in "${official_packages[@]}"; do
        local is_aur=false
        for aur_pkg in "${aur_packages[@]}"; do
            [[ "$pkg" == "$aur_pkg" ]] && is_aur=true && break
        done
        [[ "$is_aur" == "false" ]] && official_only+=("$pkg")
    done

    # Generate official package file
    local official_file="$DOTFILES_DIR/packages/hardware/gpu-${gpu_type}.package"
    {
        echo "# Auto-generated ${gpu_type^^} GPU packages"
        echo "# Generated: $(date '+%Y-%m-%d %H:%M:%S')"
        echo "# DO NOT EDIT - regenerated by hardware detection"
        echo ""
        printf '%s\n' "${official_only[@]}" | sort -u
    } > "$official_file"

    # Generate AUR package file
    local aur_file="$DOTFILES_DIR/packages/hardware/gpu-${gpu_type}-aur.package"
    {
        echo "# Auto-generated ${gpu_type^^} GPU AUR packages"
        echo "# Generated: $(date '+%Y-%m-%d %H:%M:%S')"
        echo "# DO NOT EDIT - regenerated by hardware detection"
        echo ""
        printf '%s\n' "${aur_packages[@]}" | sort -u
    } > "$aur_file"

    log_success "Generated ${gpu_type^^} packages: ${#official_only[@]} official, ${#aur_packages[@]} AUR"
}

# Install GPU packages from generated lists
hardware_packages_install() {
    log_section "Installing Hardware Packages"

    # Detect GPU
    local has_nvidia=$(has_nvidia_gpu && echo "true" || echo "false")
    local has_amd=$(has_amd_gpu && echo "true" || echo "false")
    local has_intel=$(has_intel_gpu && echo "true" || echo "false")

    # Install packages for each detected GPU
    [[ "$has_nvidia" == "true" ]] && _install_gpu_packages "nvidia"
    [[ "$has_amd" == "true" ]] && _install_gpu_packages "amd"
    [[ "$has_intel" == "true" ]] && _install_gpu_packages "intel"
}

# Internal: Install packages for a specific GPU type
_install_gpu_packages() {
    local gpu_type="$1"

    local official_file="$DOTFILES_DIR/packages/hardware/gpu-${gpu_type}.package"
    local aur_file="$DOTFILES_DIR/packages/hardware/gpu-${gpu_type}-aur.package"

    # Read official packages (skip comments)
    local official_packages=()
    if [[ -f "$official_file" ]]; then
        while IFS= read -r pkg; do
            [[ -n "$pkg" && ! "$pkg" =~ ^# ]] && official_packages+=("$pkg")
        done < "$official_file"
    fi

    # Read AUR packages (skip comments)
    local aur_packages=()
    if [[ -f "$aur_file" ]]; then
        while IFS= read -r pkg; do
            [[ -n "$pkg" && ! "$pkg" =~ ^# ]] && aur_packages+=("$pkg")
        done < "$aur_file"
    fi

    # Install official packages
    if [[ ${#official_packages[@]} -gt 0 ]]; then
        log_info "Installing ${#official_packages[@]} ${gpu_type^^} packages..."
        sudo pacman -S --needed --noconfirm "${official_packages[@]}"
        echo
    fi

    # Install AUR packages
    if [[ ${#aur_packages[@]} -gt 0 ]]; then
        ensure_yay_installed
        log_info "Installing ${#aur_packages[@]} ${gpu_type^^} AUR packages..."
        yay -S --needed --noconfirm "${aur_packages[@]}"
        echo
    fi

    log_success "✓ ${gpu_type^^} packages installed"
}

# Internal: NVIDIA post-install setup
_setup_nvidia_post_install() {
    echo
    echo "Setting up NVIDIA drivers..."

    # Build DKMS modules
    echo "Building DKMS modules (this may take a few minutes)..."
    if sudo dkms autoinstall 2>&1 | grep -q "already installed"; then
        log_success "✓ DKMS modules built"
    elif sudo dkms autoinstall >/dev/null 2>&1; then
        log_success "✓ DKMS modules built"
    else
        log_warning "DKMS build may have failed, continuing..."
    fi

    # Never load nvidia_drm in a live graphical session - it takes over DRM
    # from simpledrm/nouveau and causes an immediate blank screen/freeze.
    # A reboot is always required when the display is already up.
    if [[ -n "${WAYLAND_DISPLAY:-}" || -n "${DISPLAY:-}" ]]; then
        log_warning "⚠ Graphical session detected - skipping module load"
        log_warning "⚠ REBOOT REQUIRED for NVIDIA drivers to take effect"
        return
    fi

    # Safe to load modules only in a TTY (no graphical session)
    sudo modprobe nvidia 2>/dev/null || true
    sudo modprobe nvidia_modeset 2>/dev/null || true
    sudo modprobe nvidia_uvm 2>/dev/null || true
    sudo modprobe nvidia_drm 2>/dev/null || true

    if lsmod | grep -q "^nvidia "; then
        log_success "✓ NVIDIA driver loaded"
    else
        log_warning "⚠ REBOOT REQUIRED for NVIDIA drivers to take effect"
    fi
}

# Internal: AMD post-install setup
_setup_amd_post_install() {
    echo
    echo "Setting up AMD drivers..."

    # Load amdgpu module if not already loaded
    if lsmod | grep -q "^amdgpu "; then
        log_success "✓ AMD driver already loaded"
    else
        sudo modprobe amdgpu 2>/dev/null || true
        if lsmod | grep -q "^amdgpu "; then
            log_success "✓ AMD driver loaded"
        else
            log_warning "⚠ AMD driver may need a reboot"
        fi
    fi
}

# Internal: Intel post-install setup
_setup_intel_post_install() {
    echo
    echo "Setting up Intel drivers..."

    # Intel drivers are usually built into the kernel
    if lsmod | grep -q "^i915 "; then
        log_success "✓ Intel driver already loaded"
    else
        log_warning "⚠ Intel driver check skipped (integrated)"
    fi
}

# Internal: Create gpu.conf for Hyprland
# Show hardware package status
hardware_packages_status() {
    log_section "Hardware Package Status"

    # Detect GPU
    local has_nvidia=$(has_nvidia_gpu && echo "true" || echo "false")
    local has_amd=$(has_amd_gpu && echo "true" || echo "false")
    local has_intel=$(has_intel_gpu && echo "true" || echo "false")

    log_info "Detected GPUs:"
    [[ "$has_nvidia" == "true" ]] && log_success "  ✓ NVIDIA" || log_info "  ✗ NVIDIA"
    [[ "$has_amd" == "true" ]] && log_success "  ✓ AMD" || log_info "  ✗ AMD"
    [[ "$has_intel" == "true" ]] && log_success "  ✓ Intel" || log_info "  ✗ Intel"
    echo

    # Show installed hardware packages
    _show_gpu_packages "nvidia" "$has_nvidia"
    _show_gpu_packages "amd" "$has_amd"
    _show_gpu_packages "intel" "$has_intel"

    # Check gpu.conf (generated by Hyprland setup)
    local conf_file="$HOME/.config/hypr/gpu.conf"
    if [[ -f "$conf_file" ]]; then
        log_success "gpu.conf exists"
    else
        log_warning "gpu.conf missing (run Hyprland setup)"
    fi
}

# Internal: Show GPU package status
_show_gpu_packages() {
    local gpu_type="$1"
    local should_have="$2"

    [[ "$should_have" != "true" ]] && return

    local official_file="$DOTFILES_DIR/packages/hardware/gpu-${gpu_type}.package"
    local aur_file="$DOTFILES_DIR/packages/hardware/gpu-${gpu_type}-aur.package"

    local expected_packages=()
    [[ -f "$official_file" ]] && while IFS= read -r pkg; do
        [[ -n "$pkg" && ! "$pkg" =~ ^# ]] && expected_packages+=("$pkg")
    done < "$official_file"
    [[ -f "$aur_file" ]] && while IFS= read -r pkg; do
        [[ -n "$pkg" && ! "$pkg" =~ ^# ]] && expected_packages+=("$pkg")
    done < "$aur_file"

    [[ ${#expected_packages[@]} -eq 0 ]] && return

    log_info "${gpu_type^^} packages:"
    local missing=0
    for pkg in "${expected_packages[@]}"; do
        if pacman -Qi "$pkg" &>/dev/null; then
            printf "  ✓ %s\n" "$pkg"
        else
            printf "  ✗ %s (missing)\n" "$pkg"
            ((missing++))
        fi
    done

    [[ $missing -gt 0 ]] && log_warning "$missing ${gpu_type^^} packages missing"
    echo
}

# Show quick hardware summary for menu header
hardware_show_summary() {
    source "$DOTFILES_DIR/lib/menu.sh"

    local gpus=()
    has_nvidia_gpu && gpus+=("NVIDIA")
    has_amd_gpu && gpus+=("AMD")
    has_intel_gpu && gpus+=("Intel")

    local gpu_str="${gpus[*]:-None detected}"
    local conf_file="$DOTFILES_DIR/stow/hypr/.config/hypr/gpu.conf"
    local conf_status="missing"
    [[ -f "$conf_file" ]] && conf_status="ok"

    show_quick_summary "GPU" "$gpu_str" "gpu.conf" "$conf_status"
}

# Hardware management menu
hardware_menu() {
    source "$DOTFILES_DIR/lib/menu.sh"

    while true; do
        clear_screen "Hardware"
        hardware_show_summary

        local action=$(choose_option \
            "Setup hardware" \
            "Show details" \
            "Back")

        [[ -z "$action" ]] && return

        case "$action" in
            "Setup hardware")
                hardware_packages_setup
                ;;
            "Show details")
                run_operation "" hardware_packages_status
                ;;
            "Back")
                return
                ;;
        esac
    done
}
