pragma Singleton

// Theme variables (Generated by matugen — do not edit)
// Material You palette mapped onto base16 slots, mirroring the AGS theme
// so both shells stay visually identical.

import Quickshell
import QtQuick

Singleton {
    // Background / surface ramp (darkest -> lightest)
    readonly property color base00: "{{colors.surface_dim.default.hex}}" // Background
    readonly property color base01: "{{colors.surface.default.hex}}" // Surface
    readonly property color base02: "{{colors.surface_container_high.default.hex}}" // Selection
    readonly property color base03: "{{colors.surface_container_highest.default.hex}}" // Lines / comments
    readonly property color base04: "{{colors.on_surface_variant.default.hex}}" // Muted text
    readonly property color base05: "{{colors.on_surface.default.hex}}" // Text
    readonly property color base06: "{{colors.on_surface.default.hex}}" // Light text
    readonly property color base07: "{{colors.on_background.default.hex}}" // Primary text

    // Accent colors (Material You roles mapped to base16 hue slots)
    readonly property color base08: "{{colors.error.default.hex}}" // Red    -> error
    readonly property color base09: "{{colors.secondary.default.hex}}" // Orange -> secondary
    readonly property color base0A: "{{colors.tertiary.default.hex}}" // Yellow -> tertiary
    readonly property color base0B: "{{colors.primary.default.hex}}" // Green  -> primary
    readonly property color base0C: "{{colors.tertiary_container.default.hex}}" // Cyan   -> tertiary container
    readonly property color base0D: "{{colors.primary.default.hex}}" // Blue   -> primary
    readonly property color base0E: "{{colors.secondary_container.default.hex}}" // Purple -> secondary container
    readonly property color base0F: "{{colors.tertiary.default.hex}}" // Mauve  -> tertiary
}
