# ZSH Syntax Highlighting Colors — generated by matugen, do not edit
typeset -gA ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg={{colors.error.default.hex}}'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg={{colors.primary.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[alias]='fg={{colors.primary.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg={{colors.primary.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg={{colors.primary.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg={{colors.primary.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[function]='fg={{colors.secondary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[command]='fg={{colors.primary.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[precommand]='fg={{colors.tertiary.default.hex}},italic'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg={{colors.outline.default.hex}}'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg={{colors.primary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[path]='fg={{colors.on_surface.default.hex}},underline'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg={{colors.on_surface.default.hex}},underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg={{colors.outline.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg={{colors.outline.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg={{colors.tertiary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg={{colors.tertiary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg={{colors.tertiary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg={{colors.outline.default.hex}}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg={{colors.outline.default.hex}}'
ZSH_HIGHLIGHT_STYLES[redirection]='fg={{colors.outline.default.hex}},bold'
ZSH_HIGHLIGHT_STYLES[arg0]='fg={{colors.primary.default.hex}}'
ZSH_HIGHLIGHT_STYLES[comment]='fg={{colors.outline_variant.default.hex}},italic'
ZSH_HIGHLIGHT_STYLES[assign]='fg={{colors.on_surface_variant.default.hex}}'

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg={{colors.outline.default.hex}}"

zstyle ':completion:*:default' list-colors "=*=fg={{colors.on_surface.default.hex}};bg={{colors.surface_container_high.default.hex}}"

# EZA_COLORS — accent color for directories/executables/symlinks; tertiary for media
_h={{colors.primary.default.hex}}; _h=${_h#'#'}
_rgb="38;2;$((16#${_h:0:2}));$((16#${_h:2:2}));$((16#${_h:4:2}))"
_t={{colors.tertiary.default.hex}}; _t=${_t#'#'}
_trgb="38;2;$((16#${_t:0:2}));$((16#${_t:2:2}));$((16#${_t:4:2}))"
_media="*.mp4=${_trgb}:*.mkv=${_trgb}:*.avi=${_trgb}:*.mov=${_trgb}:*.webm=${_trgb}:*.flv=${_trgb}:*.wmv=${_trgb}:*.m4v=${_trgb}"
export EZA_COLORS="di=${_rgb}:ex=${_rgb}:ln=${_rgb}:${_media}"
unset _h _rgb _t _trgb _media
