[[mgr.prepend_keymap]]
on = ["f", "r"]
run = "plugin fr rg"
desc = "Search file by content (rg)"

[[mgr.prepend_keymap]]
on = ["f", "a"]
run = "plugin fr rga"
desc = "Search file by content (rga)"

[[mgr.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin smart-enter"
desc = "Smart enter"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Change file permissions"

[[mgr.prepend_keymap]]
on   = [ "f" ]
run  = "plugin jump-to-char"
desc = "Jump to character"

[[mgr.prepend_keymap]]
on   = [ "<C-f>" ]
run  = "plugin fzf"
desc = "FZF search"

[[mgr.prepend_keymap]]
on   = ["D"]
run = 'shell --confirm "dragon -x $@"'
desc = "Drag files with dragon"

[[mgr.prepend_keymap]]
on = ["y"]
run = [ 'shell -- wl-copy -t image/png < "$@"', "yank" ]
desc = "Yank image to clipboard"

