scheme: "Workspace"
author: "John"
base00: "000000"
base01: "191919"
base02: "333333"
base03: "71767b"
base04: "5a5a5a"
base05: "e7e9ea"
base06: "eaeaea"
base07: "ffffff"
base08: "bebebe"
base09: "c6c6c6"
base0A: "d0d0d0"
base0B: "e0e0e0"
base0C: "a0a0a0"
base0D: "b0b0b0"
base0E: "c0c0c0"
base0F: "d5d5d5"

